server:
  port: 8080

spring: 
    datasource:
        url: "jdbc:sap://ba331d5a-9060-4095-a149-25ced0779ebe.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=EXTS4_HDI_1"
        username: "EXTS4_HDI_1_AWJQ7QEDXNHDHNESBFR25MYY0_RT" 
        password: "Di8YQNcj1V3ieb_yEB.eG-S2yLAc3INS9zDmdEVNCmyB1hhmXPNpuSr.GlszvKbQJjubs4vKSo2zi17TynZyn7OTQkmUQ2R9IiMPGpK4zWu7PduTRvii9Wa0-hJc55K8"
        driver-class-name: com.sap.db.jdbc.Driver
        hikari:
            maximumPoolSize: 10
            minimumIdle: 5

VCAP_SERVICES: 
    destination: 
        label: "destination"
        provider: null
        plan: "lite"
        name: "s4h-destination"
        tags: "destination"
        tags: "conn"
        tags: "connsvc"
        instance_guid: "88653caf-9662-4957-a081-10a945b0c51a"
        instance_name: "s4h-destination"
        binding_guid: "f634b8ca-334d-4981-ad4b-ef573327406f"
        binding_name: null
        credentials: 
            uaadomain: "authentication.us10.hana.ondemand.com"
            tenantmode: "dedicated"
            clientid: "sb-clone88653caf96624957a08110a945b0c51a!b34236|destination-xsappname!b62"
            instanceid: "88653caf-9662-4957-a081-10a945b0c51a"
            verificationkey: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp8JSZm39PhSn4cPsOo/Qi2BBlQKh54t4Kh64oQ8891ZQIfCHPl2YPUZMmUJ0tjtfXhidCHyY3lYCGkwUmhlAJF+KZTYbuX4vh0xOp1Ifpa9xLi7CGF/iXaYn42uLdSLk99esEkO+XyAsWMArx5sHxoLmv8cTNwyt7vZx5MJN96w99L0GSCk0RS8KJYErfP95UssZCluLPk0xfP2NHF5BlzV9PDcR7hw94y5QYZaps/E71Nuag+q6LFiD+EAi8Bz6huEGtWPY8ZUv4hn9zoeu/O96CrZCI6zBXIGd7d9AyR0kji+YpzkdGsR0XKhd33i/1YtUswKR8vmd0qcb7xaNnQIDAQAB-----END PUBLIC KEY-----"
            xsappname: "clone88653caf96624957a08110a945b0c51a!b34236|destination-xsappname!b62"
            identityzone: "e620b360trial"
            clientsecret: "f634b8ca-334d-4981-ad4b-ef573327406f$4ZC03ToCGoqTh1hXvb6OJMqxoq43JWontMcAhnBTcDg="
            tenantid: "c00f21f3-18b8-477e-a67e-b8002604f89d"
            uri: "https://destination-configuration.cfapps.us10.hana.ondemand.com"
            url: "https://e620b360trial.authentication.us10.hana.ondemand.com"
        syslog_drain_url: null,
        volume_mounts:            
# hana:
#     url:  ${vcap.services.exts4h_hdidb.credentials.url}
#     user:  ${vcap.services.exts4h_hdidb.credentials.user}
#     password:  ${vcap.services.exts4h_hdidb.credentials.password}
    # ローカルからの接続はできなかった
    # url :  jdbc:sap://ba331d5a-9060-4095-a149-25ced0779ebe.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=6F83EB0C310C459A85620C42E4C56B8E
    # user :  6F83EB0C310C459A85620C42E4C56B8E_CFCLB86MQBAGK4ZURCK2UVJRI_RT
    # password :  Sx0Rn3NuAr3RQBaL4bi1_43NelV5kHB3f-IFvRTLNUoihdyVpAVO7aMbAHR6OuBqjxFWHCbh_PJG0vvRfwyjjn5GsNrrqq8Jm17cnuatGuuHa-WgST2wrkPI.xXfFNu7