server:
  port: 8080

spring: 
    datasource:
        url: "jdbc:sap://ba331d5a-9060-4095-a149-25ced0779ebe.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=EXTS4_HDI_1"
        username: "EXTS4_HDI_1_6HK4TJ1Q79A69S9ZHID3HJNRH_RT"
        password: "Ub47dWcypVXU7g9e9jhQb77nam-Pl7vJdKPqmMwXC8Z8KjU6VeMINtF.CjPS-Mi4cniC0wC9oHoItOTZ0.Ou.qVmtEYTMumYZHNSJ8ySXR1WMKAivbL54FMOmajgZMDN"
        driver-class-name: com.sap.db.jdbc.Driver
        
        hikari:
            maximumPoolSize: 10
            minimumIdle: 5

